apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: "arn:aws:iam::<AWS_ACCOUNT_ID>:role/<IAM_ROLE>"
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapAccounts: |
    - "<AWS_ACCOUNT_ID>"
